---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-bancario
  namespace: banco
  labels:
    app: servicio-bancario
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: servicio-bancario
  template:
    metadata:
      labels:
        app: servicio-bancario
        tier: backend
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '80'
    spec:
      containers:
        - name: servicio-bancario
          image: httpd:alpine
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: '200m'
              memory: '256Mi'
            requests:
              cpu: '100m'
              memory: '128Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-bancario-spot
  namespace: banco-spot
  labels:
    app: servicio-bancario
    tier: backend
    spot: "true"
spec:
  replicas: 0
  selector:
    matchLabels:
      app: servicio-bancario
      spot: "true"
  template:
    metadata:
      labels:
        app: servicio-bancario
        tier: backend
        spot: "true"
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '80'
    spec:
      nodeSelector:
        node.kubernetes.io/lifecycle: spot
      tolerations:
        - key: 'node.kubernetes.io/lifecycle'
          operator: 'Equal'
          value: 'spot'
          effect: 'NoSchedule'
      containers:
        - name: servicio-bancario
          image: httpd:alpine
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: '200m'
              memory: '256Mi'
            requests:
              cpu: '100m'
              memory: '128Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-bancario
  namespace: banco
  labels:
    app: servicio-bancario
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: servicio-bancario
  type: ClusterIP