apiVersion: batch/v1
kind: CronJob
metadata:
  name: spot-mover-cron
  namespace: monitoring
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: spot-mover
          restartPolicy: OnFailure
          containers:
            - name: spot-mover
              image: elvirateran/spot-mover:latest
              imagePullPolicy: Always
              command: ["python"]
              args: ["automatization.py"]
              env:
                - name: PROMETHEUS_URL
                  value: "http://prometheus-kube-prometheus-prometheus.monitoring:9090"