apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-balancer
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: load-balancer-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch", "delete", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: load-balancer-binding
subjects:
- kind: ServiceAccount
  name: load-balancer
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: load-balancer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-balancer
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      serviceAccountName: load-balancer
      containers:
      - name: load-balancer
        image: elvirateran/load-balancer:latest
        imagePullPolicy: Always
        env:
          - name: PROMETHEUS_URL
            value: "http://prometheus-kube-prometheus-prometheus.monitoring:9090"